config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'products#index'

  resources :users, only: [:show, :edit, :update] do

    member do
      get 'profile'
    end
  end
  resources :products, only: [:index, :new, :create, :show] do
    collection do
      get 'search'
    end
  end

  resources :items, only: :show do
    resources :reviews, only: [:edit, :update]
    collection do
      get 'search'
    end
  end

  resources :bookmarks, only: :create
end

app/views/shared/_flash.html.haml
- flash.each do |key, value|
  = content_tag(:div, value, class: "flash flash__#{key}")

app/views/shared/_footer.html.haml
.footer
  .wrapper
    .footer__wrapper
      .top
        .top__fortune-meetings-with-books
          %h3.footer__title
            本と出会う
          %ul
            %li ランキング
            %li 新刊情報
            %li 新着レビュー
            %li プクログ談話室
            %li プクログまとめ
            %li プクログ特集
            %li プクログ大賞
            %li プクログ通信

        .top__search-books
          %h3.footer__title
            本を探す
          %ul.search-by-keyword-or-tag
            %li キーワード
            %li タグから探す
          %h3.footer__title
            本棚を探す
          %ul.search-from-bookshelves
            %li プロフィールから本棚を探す
            %li ブクログID検索

          %h3.footer__title
            ブクログ
          %ul.applications
            %li iPhone アプリ
            %li その他のブクログアプリ

        .top__official-bookshelf
          %h3.footer__title
            公式本棚
          %ul
            %li ブクログスタッフの本棚
            %li 芥川賞の本棚
            %li 直木賞の本棚
            %li TVドラマ原作本棚
            %li 映画の原作本棚
            %li アニメの原作本棚
            %li.official-bookshelf.section-line プクログ公式本棚一覧
            %li 公式本棚の新着情報
          %h3.footer__title
            ようこそブクログへ
          %ul
            %li プクログについて
            %li 初めての方へ
            %li チュートリアル

        .top__support
          %h3.footer__title
            サポート
          %ul
            %li お知らせプクログ
            %li ヘルプ
            %li お問い合わせ
            %li.section-line 広告掲載について
            %li メディア掲載情報
            %li.section-line 公式 Twitter
            %li Facebookページ
            %li プクロぐ公式グッズ

        .top__banners
          = image_tag "bnr_booklogshop@2x.png", class:"store"
          = image_tag "bnr_bibliobattle200_65@2x.png", class:"biblio-battle"

      .SNS-btns
        = link_to " ツイート", "", class:"fa fa-twitter SNS-btn SNS-btn__twitter"
        = link_to " いいね! 1.6万", "", class:"fa fa-facebook SNS-btn SNS-btn__facebook"
        = link_to "B! ブックマーク", "", class:"SNS-btn SNS-btn__hatena"
    %ul.footer-navi
      %li.service-policy
        利用規約
        |
      %li.about-Cookie-usage
        Cookieの使用について
        |
      %li.about-us
        会社概要
        |
      %li.privacy-policy
        プライバシーポリシー

      %span.copyright-policy Copyright ©︎ 2017 Booklog.inc. All Rights Reserved

app/views/shared/_header.html.haml
.header
  .header__wrapper
    .global-navi-wrapper
      %ul.global-navi.global-navi__left
        = link_to root_path do
          = image_tag "img_booklog.png",class:"booklog-icon"
        %li.global-navi__ranking
          = link_to "ランキング", "", class:"link_to-cancel"
        %li.global-navi__release
          = link_to "新刊情報", "", class:"link_to-cancel"
        %li.global-navi__quetions
          = link_to "談話室", "", class:"link_to-cancel"
        %li.global-navi__matome
          = link_to "まとめ", "", class:"link_to-cancel"
      = form_tag(search_items_path, method: "GET", class:"search global-navi") do
        = text_field_tag :keyword, "", class:"search__input", placeholder:"作品・著者名で検索して本棚で登録"
        %i.fa.fa-question-circle.question-icon
        .search-content
          %p.introduce-text 検索キーワードの前に下記の文字列をつけて検索してください。裏ワザです。（例 @dvd 東野圭吾）
          %ul
            %li
              %span @e
              電子書籍横断検索(一般書)』 から検索
            %li
              %span @dvd
              『映画』から検索
            %li
              %span @cd
              音楽』から検索
            %li
              %span @us
              『Amazon.com』から検索
            %li
              %span @o
              『電子書籍横断検索(技術書)』から検索
            %li
              %span @p
              『パブーの電子書籍』から検索
            %li
              %span @
              『Kindleストア』から検索
            %li
              %span @i
              『iTunes Store(iPhone) 』から検索
        = button_tag "" , class: 'search__search-btn fa fa-search', type: :submit
      - if user_signed_in?
        %ul.global-navi.global-navi__right
          %li.global-navi__user-icon-header
            - if current_user.avatar.present?
              = image_tag current_user.avatar, class:"user-icon-header"
            - else
              = image_tag "user-icon.png", class:"user-icon-header"
            .dropdown-user-icon
              %ul
                %li.bar-border
                  = link_to "#{current_user.nickname}さん", profile_user_path(current_user), class:"fa fa-user"
                %li
                  = link_to "本の並び替え", "", class:"fa fa-th"
                %li
                  = link_to "カテゴリーの編集・削除", "", class:"fa fa-folder"
                %li.bar-border
                  = link_to "タグの編集・削除", "", class:"fa fa-tags"
                %li
                  = link_to "本棚の設定", "", class:"fa fa-cog"
                %li.bar-border
                  = link_to "プロフィールの設定", edit_user_path(current_user), class:"fa fa-smile-o"
                %li
                  =link_to "ログアウト", destroy_user_session_path,method: :DELETE, class:"fa fa-sign-out"

          %li.global-navi__home
            = link_to "", profile_user_path(current_user), class:"fa fa-home link_to-cancel"
            .hover-icon
              .hover-icon.hover-icon__home-icon
                %span ホーム
          %li.global-navi__bookshelf
            = link_to "", user_path(current_user), class:"fa fa-book link_to-cancel"
            .hover-icon
              .hover-icon.hover-icon__bookshelf-icon
                %span 本棚
          %li.global-navi__timeline
            = link_to "", "", class:"fa fa-clock-o link_to-cancel"
            .hover-icon
              .hover-icon.hover-icon__timeline-icon
                %span タイムライン
          %li.global-navi__dropdown-menu-click
            %i.fa.fa-bars
            .dropdown-menu-icon
              %ul
                %li
                  = link_to "ブックログ公式本棚", "", class:"fa fa-heart"
                %li.bar-border
                  = link_to "ブックログ特集", "", class:"fa fa-diamond"
                %li
                  = link_to "ブックログのアプリ", "", class:"fa fa-mobile"
                %li.bar-border
                  = link_to "チュートリアル", "", class:"fa fa-check-square-o"
                %li
                  = link_to "お知らせブログ", "", class:"fa fa-info-circle"
                %li
                  = link_to "ヘルプ", "", class:"fa fa-question-circle"
                %li.bar-border
                  = link_to "ブックログ公式グッズ", "", class:"fa fa-shopping-cart"
                %li
                  = link_to "Twitterをフォロー", "", class:"fa fa-twitter"
                %li
                  = link_to "Facebookページ", "", class:"fa fa-facebook-square"
      - else
        %ul.global-navi.global-navi__right
          %li.global-navi__mypage
          %li
            %span.devise-btns.user-create-btn
              = link_to "新規登録", new_user_registration_path
              %i.fa.fa-facebook-square
              %i.fa.fa-twitter-square

          %li
            = link_to "ログイン", new_user_session_path,class:"devise-btns user-sign_in-btn"
          %li.global-navi__dropdown-menu-click
            = link_to "", "", class:"fa fa-bars link_to-cancel"


  %ul.info
    %li.icon NEW
    %li.news-text
      = link_to "11月公開映画「ラストレシピ」", "", class:"news-text"