config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'products#index'

  resources :users, only: [:show, :edit, :update] do

    member do
      get 'profile'
    end
  end
  resources :products, only: [:index, :new, :create, :show] do
    collection do
      get 'search'
    end
  end

  resources :items, only: :show do
    resources :reviews, only: [:edit, :update]
    collection do
      get 'search'
    end
  end

  resources :bookmarks, only: :create
end

app/models/item.rb
class Item
  include ActiveModel::Model
  attr_accessor :id,:isbn, :name, :image, :author, :publisher, :release_date
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def show
      @bookmark = Bookmark.new
      openBD_uri = URI.parse('https://api.openbd.jp/v1/get?isbn=' + params[:id])
      openBD_json = Net::HTTP.get(openBD_uri)
      openBD_result = JSON.parse(openBD_json).to_a
      data = openBD_result[0]

      @item = Item.new(isbn: data["summary"]["isbn"],
                          name: data["summary"]["title"],
                          image: data["summary"]["cover"],
                          author: data["summary"]["author"],
                          publisher: data["summary"]["publisher"],
                          release_date: data["summary"]["pubdate"])
      @review = Review.find_or_create_by(isbn: params[:id], user_id: current_user.id) if user_signed_in?
      @reviews = Review.where(isbn: params[:id])
      @review_total = @reviews.where.not(body: nil).length
      @average_rate = @reviews.average(:rate)
      @total_bookmarks = @reviews.length
  end

  def search
    @bookmark = Bookmark.new

# GoogleBooksApiから入力されたkeywordに基づいてisbn番号を取得
    if params[:keyword].present?
      input = URI.encode_www_form({q: params[:keyword]})

      uri = URI.parse('https://www.googleapis.com/books/v1/volumes?' + input)
      json = Net::HTTP.get(uri)
      result = JSON.parse(json).to_a
      isbn_tmp_list = []
      isbn_list = []

# result[2][1]に各アイテムの情報が並んでいるのでそれに対して処理
      result[2][1].each_with_index do |item, i|
        if result[2][1][i]["volumeInfo"]["industryIdentifiers"]
          if result[2][1][i]["volumeInfo"]["industryIdentifiers"].length == 1 || result[2][1][i]["volumeInfo"]["industryIdentifiers"].length == 2

            isbn_tmp_list << result[2][1][i]["volumeInfo"]["industryIdentifiers"]
          end
        end
      end

      isbn_tmp_list.each do |row|
        i = 0
        row.each do |item|
          if item["identifier"].match(/^\d{10}$/) || item["identifier"].match(/^\d{13}$/)
            isbn_list << item["identifier"]
            i = i + 1
           if i = 1 then
              break
            end
          end
        end
      end

      @isbn_list = isbn_list.uniq.map(&:to_i)

# GoogleBooksAPIでとってきたISBNをOpenBDAPIに投げる
      openBD_uri = URI.parse('https://api.openbd.jp/v1/get?isbn=' +"#{ @isbn_list}")
      openBD_json = Net::HTTP.get(openBD_uri)
      openBD_result = JSON.parse(openBD_json).to_a

      @openBD_result = openBD_result
      @search_results = []

      @openBD_result.each_with_index do |data, i|
        if data.present?
          item = Item.new(isbn: data["summary"]["isbn"],
                          name: data["summary"]["title"],
                          image: data["summary"]["cover"],
                          author: data["summary"]["author"],
                          publisher: data["summary"]["publisher"],
                          release_date: data["summary"]["pubdate"])
          @search_results << item
        end
      end
    end
  end

end

app/views/items/_review.html.haml
- if review.body.present? && review.public_status == 0
  %ul.review-area
    .user-icon
      - if review.user.avatar.present?
        = image_tag review.user.avatar,class:"user-image"
      - else
        = image_tag "user-icon.png",class:"user-image"
    .review-area__summary{spoiler_status: review.spoiler_status}
      .review-area__summary__user-info
        = link_to "#{review.user.nickname}さん", user_path(review.user)
        のレビュー
      .review-area__summary__rating
        - review.rate.times do
          %i.fa.fa-star
        - (5 - review.rate).times do
          %i.fa.fa-star-o
        %span
          = link_to "" do
            = review.set_created_at
      .review-area__summary__review-text
        %p
          = review.body
      .review-area__summary__reaction
        = link_to do
          = image_tag "btn/like-btn.png",class:"review-area__summary__reaction-like"
        %span.like-count
          23
        = link_to "コメントする", "",class:"review-area__summary__reaction-comment"

app/views/items/_search-result.html.haml
.search-wrapper__result
  .search-wrapper__result-top
    .product-name
      = link_to result.name,item_path(result.isbn)
    %ul
      %li.product-evaluation.product-evaluation__count
        = Bookmark.where(isbn: result.isbn).length
        人が登録
      %li.product-evaluation.product-evaluation__average
        %i.fa.fa-star
        = Review.where(isbn: result.isbn).average(:rate)
      %li.product-evaluation.product-evaluation__review
        = Review.where(isbn: result.isbn).length
        レビュー
    .product-info
      %span 雑誌
      %span
        = result.release_date
      %span
        = image_tag "store/amazon-mini.gif"
        Amazon.co.jpで見る
  .search-wrapper__result-image
    - if result.image.present?
      = image_tag result.image, class:"image-import"
    - else
      = image_tag "no_image.png", class:"image-import"
  .search-wrapper__result-register
    = form_for @bookmark do |f|
      = f.hidden_field :isbn, value:"#{result.isbn}"
      - if Bookmark.where(isbn: result.isbn, user_id: current_user.id).present?
        = link_to "", edit_item_review_path(result.isbn, Review.find_by(isbn: result.isbn, user_id: current_user.id)), class:"add-product-btn-review"
      - else
        = f.submit "", class:"add-product-btn"
      = link_to "", "", class:"add-product-btn-secretly"

app/views/items/search.html.haml
= render 'shared/header'
= render 'shared/flash'
.body

  .wrapper
    %ul.breadcrumbs
      %li.breadcrumbs__home
        %a{href:""} 仮
      %li.breadcrumbs__current-page
        >  仮です
    .profile-setting
      本の検索

    .search-area
      = form_tag "search", method: :GET do
        = text_field_tag :keyword, "", class:"search-area__input", placeholder:"作品・著者名で検索して本棚で登録"
        = select_tag :service_id, options_for_select([["Amazon.co.jp", "1"], ["Amazon.com", "2"], ["パブー", "3"], ["iTunes Store", "4"], ["青空文庫", "5"], ["電子書籍(一般書)", "6"], ["電子書籍(技術書)", "7"]])
        = select_tag :genre, options_for_select([["本", "1"], ["Kindleストア", "2"], ["洋書", "3"], ["DVD", "4"], ["音楽", "5"], ["ゲーム", "6"], ["すべての商品", "7"]])
        = button_tag "" , class: 'submit-btn', type: :submit do
          %i.fa.fa-search

    .lead
      まずは商品名、著者名、出版社名などを入力して検索してください。
      %br
      例えば...
      = link_to "村上春樹",""
      や
      = link_to "宇多田ヒカル",""
      や
      = link_to "ジブリ",""
      など。

    %h3.search-area__tags
      <検索キーワード>の作品ランキング・新刊情報・電子書籍

    .search-area__sort
      = link_to "おすすめ順","",class:"search-area__sort-btn"
      = link_to "人気順","",class:"search-area__sort-btn"
      = link_to "レビュー数順","",class:"search-area__sort-btn"
      = link_to "新刊情報","",class:"search-area__sort-btn"
      = link_to "電子書籍","",class:"search-area__sort-btn"

    %ul.tab-menu
      %li
        = link_to "すべての本",""
      %li
        = link_to "紙の本",""
      %li
        = link_to "Kindle",""

    .search-wrapper
      %ul.search-wrapper__order
        %li.search-wrapper__order-title
          並び:
        %li.search-wrapper__order-recommend
          おすすめ順
        %li
          = link_to "発売日順","",class:"search-wrapper__order-release-date"
      = render partial: "search-result",collection: @search_results, as:"result"


    .side-bar
      .advertisement
      .side-bar__title
        本の登録・編集
      .side-bar__list
        %p.side-bar__subtitle
          本を登録する
        %ul
          %li
            = link_to "キーワードで検索"
          %li
            = link_to "タグから検索"""
          %li
            = link_to "まとめて登録(ISBN)"
          %li
            = link_to "ブックマックレートで登録"
          %li
            = link_to "オリジナルアイテム登録"

        %p.side-bar__subtitle
          編集する
        %ul
          %li
            = link_to "本の並び替え"
          %li
            = link_to "カテゴリの編集・削除"
          %li
            = link_to "タグの編集・削除"
          %li
            = link_to "読書状況まとめて変更"
          %li
            = link_to "コメント一覧"
          %li
            = link_to "まとめて削除"

        %p.side-bar__subtitle
          外部で活用する
        %ul
          %li
            = link_to "まとめて紹介リンク作成"
          %li
            = link_to "本棚ブログパーツ作成"
          %li
            = link_to "エクスポート"

= render 'shared/footer'