config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'products#index'

  resources :users, only: [:show, :edit, :update] do

    member do
      get 'profile'
    end
  end
  resources :products, only: [:index, :new, :create, :show] do
    collection do
      get 'search'
    end
  end

  resources :items, only: :show do
    resources :reviews, only: [:edit, :update]
    collection do
      get 'search'
    end
  end

  resources :bookmarks, only: :create
end

app/models/product.rb
class Product < ApplicationRecord
 mount_uploader :image, ImageUploader
 validates :name, presence: true, uniqueness: :true
 validates :author, presence: true
 validates :publisher, presence: true

 has_many :reviews
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :admin_user,only:[:new, :create]

  def index
    @reviews = Review.all
    @review_books = []
    @review_books_results = []

    @bookmarks = Bookmark.all.order("id DESC")
    @bookmark_books = []
    @bookmark_books_results = []

    @ranking_books = []
    @ranking_books_results = []


    @reviews.each do |review|
      openBD_uri = URI.parse('https://api.openbd.jp/v1/get?isbn=' +"#{ review.isbn}")
      openBD_json = Net::HTTP.get(openBD_uri)
      openBD_result = JSON.parse(openBD_json).to_a

      @review_books << openBD_result
    end


    @review_books.each_with_index do |data, i|
      if data.present?
        item = Item.new(isbn: data[0]["summary"]["isbn"],
                        name: data[0]["summary"]["title"],
                        image: data[0]["summary"]["cover"],
                        author: data[0]["summary"]["author"],
                        publisher: data[0]["summary"]["publisher"],
                        release_date: data[0]["summary"]["pubdate"])
        @review_books_results << item
      end
    end

    @bookmarks.each do |bookmark|
      openBD_uri = URI.parse('https://api.openbd.jp/v1/get?isbn=' +"#{ bookmark.isbn}")
      openBD_json = Net::HTTP.get(openBD_uri)
      openBD_result = JSON.parse(openBD_json).to_a

      @bookmark_books << openBD_result
    end

    @bookmark_books.each_with_index do |data, i|
      if data.present?
        item = Item.new(isbn: data[0]["summary"]["isbn"],
                        name: data[0]["summary"]["title"],
                        image: data[0]["summary"]["cover"],
                        author: data[0]["summary"]["author"],
                        publisher: data[0]["summary"]["publisher"],
                        release_date: data[0]["summary"]["pubdate"])
        @bookmark_books_results << item
      end
    end
    @bookmark_books_results.uniq!{|n| n.name}

    ranking_isbn_lists = Bookmark.group(:isbn).order('count_isbn DESC').count(:isbn).keys
    ranking_isbn_lists.each do |isbn|
      openBD_uri = URI.parse('https://api.openbd.jp/v1/get?isbn=' +"#{isbn}")
      openBD_json = Net::HTTP.get(openBD_uri)
      openBD_result = JSON.parse(openBD_json).to_a

    @ranking_books << openBD_result
    end

    @ranking_books.each_with_index do |data, i|
      if data.present?
        item = Item.new(isbn: data[0]["summary"]["isbn"],
                        name: data[0]["summary"]["title"],
                        image: data[0]["summary"]["cover"],
                        author: data[0]["summary"]["author"],
                        publisher: data[0]["summary"]["publisher"],
                        release_date: data[0]["summary"]["pubdate"])
        @ranking_books_results << item
      end
    end
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to :root
    else
      render :new
    end
  end

  def show
    @product = Product.find(params[:id])
    @review_total = @product.reviews.where.not(body: nil).length
    @average_rate = @product.reviews.average(:rate)
    @review = Review.find_or_create_by(product_id: params[:id], user_id: current_user.id) if user_signed_in?
  end

  def search
  end

private
  def product_params
    params.require(:product).permit(:name, :image, :author, :publisher, :release_date)
  end

  def admin_user
    redirect_to :root unless current_user.admin?
  end
end

app/views/products/_late_review.html.haml
- if review.body.present?
  .review-container
    = link_to item_path(@review_books_results[review_counter].isbn) do
      - if @review_books_results[review_counter].image.present?
        = image_tag @review_books_results[review_counter].image,class:"review-container__image"
      - else
        = image_tag "no_image.png",class:"review-container__image"
    .review-container__product-info
      %span.review-container__product-info__title
        = link_to @review_books_results[review_counter].name, item_path(@review_books_results[review_counter].isbn)
      .review-container__product-info__author
        = link_to @review_books_results[review_counter].author, item_path(@review_books_results[review_counter].isbn)
    .review-container__review
      .user-info
        .user-name
          = review.user.nickname
        .rating
          - review.rate.times do
            %i.fa.fa-star
          - (5 - review.rate).times do
            %i.fa.fa-star-o
      .review-text
        .review-text__body
          = review.body
        .review-text__like-count
          = image_tag "faving.gif"

app/views/products/_lately_registerd.html.haml
.release-container
  = link_to item_path(book.isbn) do
    - if book.image.present?
      = image_tag book.image,class:"review-container__image"
    - else
      = image_tag "no_image.png",class:"review-container__image"
  .release-container__product-info
    .release-container__product-info__title
      = link_to book.name, item_path(book.isbn)
    .release-container__product-info__author
      = link_to book.author, item_path(book.isbn)
    .release-container__product-info__publish-date
      = book.release_date
  .release-container__date

app/views/products/_ranking.html.haml
.ranking-container
  = link_to item_path(ranking.isbn) do
    - if ranking.image.present?
      = image_tag ranking.image,class:"review-container__image"
    - else
      = image_tag "no_image.png",class:"review-container__image"
  .ranking-container__product-info
    .ranking-container__product-info__title
      = link_to ranking.name, item_path(ranking.isbn)
    .ranking-container__product-info__author
      = link_to ranking.author, item_path(ranking.isbn)
    .ranking-container__evaluation
      = link_to "#{Bookmark.where(isbn: ranking.isbn).length}人が登録","",class:"ranking-container__evaluation__registration-number"
      = link_to "#{Review.where(isbn: ranking.isbn).average(:rate)}", "", class:"fa fa-star ranking-container__evaluation__average"
      %span.ranking-container__evaluation__recent-registration-number 最近69人が登録

app/views/products/_search-result.html.haml
.search-wrapper__result
  .search-wrapper__result-top
    .product-name
      = link_to "テニスクラシックBreak 2017年 12 月号 [雑誌]",""
    %ul
      %li.product-evaluation.product-evaluation__count
        1人が登録
      %li.product-evaluation.product-evaluation__average
        %i.fa.fa-star
        4.00
      %li.product-evaluation.product-evaluation__review
        1レビュー
    .product-info
      %span 雑誌
      %span 2017年11月4日
      %span
        = image_tag "store/amazon-mini.gif"
        Amazon.co.jpで見る
  .search-wrapper__result-image
    = image_tag "karioki2.jpg"
  .search-wrapper__result-register
    = link_to "", "", class:"add-product-btn"
    = link_to "", "", class:"add-product-btn-secretly"

app/views/products/index.html.haml
= render 'shared/header'
= render 'shared/flash'

.body
  .wrapper
    .top-page
      = image_tag "bnr_winner2017_970_230.png",class:"booklog-award"
    .middle-page
      %ul.recommend-list
        %li.recommend-list__1
          = image_tag "bb-200.png"
        %li.recommend-list__2
          = image_tag "bnr_200_65.png"
        %li.recommend-list__3
          = image_tag "bnr_bukutsu200_65.png"
        %li.recommend-list__4
          = image_tag "bnr_itengineer2017_200_65.png"

      .middle-page-content
        .middle-page-content__popular-review
          %h2.top-title
            最新のレビュー
          = render partial: "late_review", collection: @reviews, as:"review"
          .more-btn
            = link_to "もっとみる", "", class:"more-btn__body"
        .middle-page-content__ranking
          %h2.top-title
            登録者数ランキング
          = render partial: "ranking", collection: @ranking_books_results, as:"ranking"
          .more-btn
            = link_to "もっとみる", "", class:"more-btn__body"

        .middle-page-content__release
          %h2.top-title
            最近登録された本
          = render partial: "lately_registerd", collection: @bookmark_books_results, as:"book"

          .more-btn
            = link_to "もっとみる", "", class:"more-btn__body"
        .popular-author
          %h3.popular-author__heading
            話題の作家
          %ul.hot-authors
            - 45.times do
              %li
                = link_to "青山", "", class:"authors-name"
              %li
              = link_to "青山", "", class:"authors-name"

          %h3.popular-author__heading
            人気の作家のおすすめ本・新刊情報・電子書籍
          %ul.popular-authors
            - 45.times do
              %li
                = link_to "田中", "", class:"authors-name"
              %li
                = link_to "田中", "", class:"authors-name"

        .advertisement
        .total-amount-of-numbers-about-booklog
          %span ブクログは、
          %span.red 104万5403人
          %span の利用者が、
          %span.red 7751万4529アイテム
          %span を登録して、
          %span.red 812万5116件のレビュー
          %span を書いています。

= render 'shared/footer'

app/views/products/new.html.haml
.body
  %h1 作品登録
  = form_for @product do |f|
    .registration-wrapper
      .registration-form__title-box
        .registration-form__left-content
          .field-label
            = f.label :name, "タイトル", class: "registration-form__label"
        .registration-form__right-content
          .field-label
            = f.text_field :name, placeholder: "タイトルを入力してください", class: "registration-form__input"

      .registration-form__author-box
        .registration-form__left-content
          .field-label
            = f.label :author, "著者", class: "registration-form__label"
        .registration-form__right-content
          .field-label
            = f.text_field :author, placeholder: "著者を入力してください", class: "registration-form__input"

      .registration-form__image-box
        .registration-form__left-content
          .field-label
            = f.label :image, "画像", class: "registration-form__label"
        .registration-form__right-content
          .field-label
            = f.file_field :image, placeholder: "", class: "registration-form"

      .registration-form__publisher-box
        .registration-form__left-content
          .field-label
            = f.label :publisher, "出版社", class: "registration-form__label"
        .registration-form__right-content
          .field-label
            = f.text_field :publisher, placeholder: "出版社を入力してください", class: "registration-form__input"

      .registration-form__release-box
        .registration-form__left-content
          .field-label
            = f.label :release_date, "発売日", class: "registration-form__label"
        .registration-form__right-content
          .field-label
            = f.date_select(:release_date, {}, use_month_numbers: true, class: "release-date")

      .button
        .registration-form
          .field-label
            = f.submit "登録する", class: "registration-form__btn"

app/views/products/show.html.haml
= render 'shared/header'
= render 'shared/flash'

- content_for(:head) do
  %meta{name:"turbolinks-cache-control", content:"no-cache"}

.body
  .wrapper
    %ul.breadcrumbs
      %li.breadcrumbs__home
        = link_to "仮"
      %li.breadcrumbs__home
        = link_to "> 仮"
      %li.breadcrumbs__current-page
        >  仮です

    .wrapper-product-show
      .product-wrapper
        .product-wrapper__title
          = @product.name
        .product-wrapper__left
          = link_to "" do
            = image_tag @product.image, class:"product-wrapper__image"
          = link_to "", edit_product_review_path(@product.id, @review.id), class:"book-btn"
        .product-wrapper__info
          %ul.product-wrapper__info__status
            %li
              %i.fa.fa-user
              %span 40
              人登録
            %li
              %i.fa.fa-star
              %span
                = @average_rate
              評価
            %li
              %i.fa.fa-comment
              %span
                = @review_total
              人レビュー
          .product-wrapper__info__author
            著者:
            = link_to @product.author,""
          .product-wrapper__info__publisher
            %span.company-name
              = @product.publisher
            %span.release-date
              = @product.release_date.strftime("(%Y年%m月%d日発売)")
          = link_to "" do
            = image_tag "amazon-btn.png",class:"product-wrapper__info__btn-amazon"
          %ul.product-wrapper__info__btn-others
            %li
              = link_to "" do
                = image_tag "btn/honto_logo.png",class:"main-shop-btn"
            %li
              = link_to "" do
                = image_tag "btn/rakuten_logo.png",class:"main-shop-btn"
            %li
              = link_to "" do
                = image_tag "btn/bol_logo.png",class:"main-shop-btn"
            %li
              = link_to "" do
                = image_tag "btn/calil_logo.png",class:"main-shop-btn"
            %li
              = link_to "" do
                = image_tag "btn/other_store.png",class:"other-shop-btn"
        .product-wrapper__more
          .product-wrapper__more__link
            = link_to do
              %i.fa.fa-file-code-o
              サイトに貼り付ける
          .product-wrapper__more__info
            Amazon.co.jp ・本 (192ページ)  / ISBN・EAN: 9784405082168
      .review-wrapper
        .row-title
          この本を読んでいる人は、こんな本も本棚に登録しています。

        .slick_container
          %ul.main-thumb
            %li
              = image_tag "book__review__karioki.jpg"
            %li
              = image_tag "karioki2.jpg"
            %li
              = image_tag "karioki3.jpg"
            %li
              = image_tag "karioki4.jpg"
            %li
              = image_tag "karioki5.jpg"
          #arrows
            .slick-next
              = image_tag "btn/arrow-right-enable.png",class:"customed-btn"
            .slick-prev
              = image_tag "btn/arrow-left-enable.png",class:"customed-btn"

      .review-wrapper
        .row-title
          #{@product.name}の教科書の感想・レビュー・書評

        %ul.review-wrapper__sort-by-rating
          %li
            = link_to "すべてのレビュー"
          %li
            = link_to "評価★5"
          %li
            = link_to "評価★4"
          %li
            = link_to "評価★3"
          %li
            = link_to "評価★2"
          %li
            = link_to "評価★1"

        = render partial: "review", collection: @product.reviews

        %ul.review-more-btns
          %li.review-more-btns-amazon
            = link_to "" do
              = image_tag "btn/btn_read_more_amazon.png",class:"review-more-btn"
          %li.review-more-btns-rakuten
            = link_to "" do
              = image_tag "btn/btn_read_more_rakuten.png",class:"review-more-btn"

        %ul.social-btn-box-area
          %li.social-btn-box-area__list
            = link_to "" do
              = image_tag "btn/btn_tweet_box.png",class:"twitter-btn"
          %li.social-btn-box-area__list.social-btn-box-area__list-facebook
            = link_to "" do
              %span
                15
                = image_tag "btn/FB-like-btn.png",class:"facebook-btn"
            = link_to "" do
              %span
                15
                = image_tag "btn/FB-share-btn.png",class:"facebook-btn"
          %li.social-btn-box-area__list.social-btn-box-area__list-hatena
            = link_to "" do
              %span
                15
                = image_tag "btn/hatena-bookmark-btn.png",class:"hatena-btn"

        .additional-info-area
          %h2.area-title
            作者の名前の作品一覧
          %ul.additional-info-area__book-list.additional-info-area__book-list-left
            %li
              = link_to "サンプルテキスト(ジャンプ・コミックス)", ""
            %li
              = link_to "サンプルテキスト(ジャンプ・コミックス)", ""
            %li
              = link_to "サンプルテキスト(ジャンプ・コミックス)", ""
            %li
              = link_to "サンプルテキスト(ジャンプ・コミックス)", ""
            %li
              = link_to "サンプルテキスト(ジャンプ・コミックス)", ""
            %li
              = link_to "サンプルテキスト(ジャンプ・コミックス)", ""
          %ul.additional-info-area__book-list.additional-info-area__book-list-right
            %li
              = link_to "サンプルテキスト(ジャンプ・コミックス)", ""
            %li
              = link_to "サンプルテキスト(ジャンプ・コミックス)", ""
            %li
              = link_to "サンプルテキスト(ジャンプ・コミックス)", ""
            %li
              = link_to "サンプルテキスト(ジャンプ・コミックス)", ""
            %li
              = link_to "サンプルテキスト(ジャンプ・コミックス)", ""
            %li
              = link_to "サンプルテキスト(ジャンプ・コミックス)", ""
          %p.additional-info-area__link
            = link_to "尾田栄一郎の作品ランキング・新刊情報"

        .additional-info-area
          %h2.area-title
            外部サイトの商品情報・レビュー
          %p.additional-info-area__link
            = link_to "Amazonでレビューを見る"
          %p.additional-info-area__link
            = link_to "カーリルで図書館の貸し出し状況を見る"
          %p.additional-info-area__link
            = link_to "Webcat Plus(国立情報学研究所)で図書情報を見る"

        .user-status-area
          .user-status-area__reading-status-box
            %h2.area-title
              #{@product.name}を本棚に登録しているひと
            %ul.user-status-area__user-row
              %li
                = link_to "users/" do
                  .user-icon
                    = image_tag "user-icon.png",class:"user-image"
                  .user-text
                    .user-text__name
                      お名前
                    .user-text__rating
                      %i.fa.fa-star-o
                      %i.fa.fa-star-o
                      %i.fa.fa-star-o
                      %i.fa.fa-star-o
                      %i.fa.fa-star-o
                    .user-text__created_at
                      2017年1月2日に登録
              %li
                = link_to "" do
                  .user-icon
                    = image_tag "user-icon.png",class:"user-image"
                  .user-text
                    .user-text__name
                      お名前
                    .user-text__rating
                      %i.fa.fa-star-o
                      %i.fa.fa-star-o
                      %i.fa.fa-star-o
                      %i.fa.fa-star-o
                      %i.fa.fa-star-o
                    .user-text__created_at
                      2017年1月2日に登録

              %li
                = link_to "users/" do
                  .user-icon
                    = image_tag "user-icon.png",class:"user-image"
                  .user-text
                    .user-text__name
                      お名前
                    .user-text__rating
                      %i.fa.fa-star-o
                      %i.fa.fa-star-o
                      %i.fa.fa-star-o
                      %i.fa.fa-star-o
                      %i.fa.fa-star-o
                    .user-text__created_at
                      2017年1月2日に登録
          .user-status-area__reading-status-box
            %h2.area-title
              #{@product.name}を「読みたい」で本棚に登録しているひと
              %ul.user-status-area__user-row
                %li
                  = link_to "users/" do
                    .user-icon
                      = image_tag "user-icon.png",class:"user-image"
                    .user-text
                      .user-text__name
                        お名前
                      .user-text__rating
                        %i.fa.fa-star-o
                        %i.fa.fa-star-o
                        %i.fa.fa-star-o
                        %i.fa.fa-star-o
                        %i.fa.fa-star-o
                      .user-text__created_at
                        2017年1月2日に登録
                %li
                  = link_to "" do
                    .user-icon
                      = image_tag "user-icon.png",class:"user-image"
                    .user-text
                      .user-text__name
                        お名前
                      .user-text__rating
                        %i.fa.fa-star-o
                        %i.fa.fa-star-o
                        %i.fa.fa-star-o
                        %i.fa.fa-star-o
                        %i.fa.fa-star-o
                      .user-text__created_at
                        2017年1月2日に登録

                %li
                  = link_to "users/" do
                    .user-icon
                      = image_tag "user-icon.png",class:"user-image"
                    .user-text
                      .user-text__name
                        お名前
                      .user-text__rating
                        %i.fa.fa-star-o
                        %i.fa.fa-star-o
                        %i.fa.fa-star-o
                        %i.fa.fa-star-o
                        %i.fa.fa-star-o
                      .user-text__created_at
                        2017年1月2日に登録
          .user-status-area__reading-status-box
            %h2.area-title
              #{@product.name}を「いま読んでる」で本棚に登録しているひと
              %ul.user-status-area__user-row
                %li
                  = link_to "users/" do
                    .user-icon
                      = image_tag "user-icon.png",class:"user-image"
                    .user-text
                      .user-text__name
                        お名前
                      .user-text__rating
                        %i.fa.fa-star-o
                        %i.fa.fa-star-o
                        %i.fa.fa-star-o
                        %i.fa.fa-star-o
                        %i.fa.fa-star-o
                      .user-text__created_at
                        2017年1月2日に登録
                %li
                  = link_to "" do
                    .user-icon
                      = image_tag "user-icon.png",class:"user-image"
                    .user-text
                      .user-text__name
                        お名前
                      .user-text__rating
                        %i.fa.fa-star-o
                        %i.fa.fa-star-o
                        %i.fa.fa-star-o
                        %i.fa.fa-star-o
                        %i.fa.fa-star-o
                      .user-text__created_at
                        2017年1月2日に登録
          .user-status-area__reading-status-box
            %h2.area-title
              #{@product.name}を「読み終わった」で本棚に登録しているひと
              %ul.user-status-area__user-row
                %li
                  = link_to "users/" do
                    .user-icon
                      = image_tag "user-icon.png",class:"user-image"
                    .user-text
                      .user-text__name
                        お名前
                      .user-text__rating
                        %i.fa.fa-star-o
                        %i.fa.fa-star-o
                        %i.fa.fa-star-o
                        %i.fa.fa-star-o
                        %i.fa.fa-star-o
                      .user-text__created_at
                        2017年1月2日に登録
                %li
                  = link_to "" do
                    .user-icon
                      = image_tag "user-icon.png",class:"user-image"
                    .user-text
                      .user-text__name
                        お名前
                      .user-text__rating
                        %i.fa.fa-star-o
                        %i.fa.fa-star-o
                        %i.fa.fa-star-o
                        %i.fa.fa-star-o
                        %i.fa.fa-star-o
                      .user-text__created_at
                        2017年1月2日に登録
          .user-status-area__reading-status-box
            %h2.area-title
              #{@product.name}を「積読」で本棚に登録しているひと
              %ul.user-status-area__user-row
                %li
                  = link_to "users/" do
                    .user-icon
                      = image_tag "user-icon.png",class:"user-image"
                    .user-text
                      .user-text__name
                        お名前
                      .user-text__rating
                        %i.fa.fa-star-o
                        %i.fa.fa-star-o
                        %i.fa.fa-star-o
                        %i.fa.fa-star-o
                        %i.fa.fa-star-o
                      .user-text__created_at
                        2017年1月2日に登録
                %li
                  = link_to "" do
                    .user-icon
                      = image_tag "user-icon.png",class:"user-image"
                    .user-text
                      .user-text__name
                        お名前
                      .user-text__rating
                        %i.fa.fa-star-o
                        %i.fa.fa-star-o
                        %i.fa.fa-star-o
                        %i.fa.fa-star-o
                        %i.fa.fa-star-o
                      .user-text__created_at
                        2017年1月2日に登録

= render 'shared/footer'